### ISSUE TITLE
Add installation manual

### ISSUE THREAD

**Issue by begarco** [lequal/cnes-pylint-extension#4]
### Expected behavior
The installation manual should be accessible by users.

### Actual behavior
The installation manual is only accessible by CNES.

### Steps to reproduce behavior
Read the doc.

### Detection version
4.0

**Comment by Sancretor** [comment]
HI @begarco,

The [#to-use-these-checkers](https://github.com/lequal/cnes-pylint-extension#to-use-these-checkers) is not enough ?
Which user manual are you referring to ?
